version: 0.0
os: linux
files:
        - source: app.service
          destination: /usr/lib/systemd/system/
        - source: .build/valor
          destination: /valiu
        - source: plugins.json
          destination: /valiu
        - source: .build/plugins
          destination: /valiu

hooks:
        BeforeInstall:
                - location: move_prev_version
        AfterInstall:
                - location: change_permissions
                - location: enable_service
        ApplicationStart:
                - location: start_service
        ApplicationStop:
                - location: stop_service
        ValidateService:
                - location: check_service

